
# tools
Bbduk=/research/groups/mackgrp/home/common/Tools/ExTools/bbmap-39.01/bbduk.sh
Repair=/research/groups/mackgrp/home/common/Tools/ExTools/bbmap-39.01/repair.sh
UMI_Tools=/research/groups/mackgrp/home/common/Tools/ExTools/extra/miniconda3/bin/umi_tools
